"""Framework-independent business data owned by the Pixel Agents package."""

from .office import (
    ActivityKind,
    ActivitySnapshot,
    AgentId,
    AgentKey,
    AgentSnapshot,
    GenuineAgentKey,
    MessageSnapshot,
    OfficeIdentity,
    PresenceStatus,
    SnowflakeId,
)
from .office_ir import (
    Direction,
    FurnitureItem,
    FurnitureKind,
    Grid,
    GridPosition,
    GridRect,
    Occupant,
    Office,
    Seat,
    TileCell,
    TileKind,
    Zone,
)
from .settings import parse_commit_ref

__all__ = [
    "ActivityKind",
    "ActivitySnapshot",
    "AgentId",
    "AgentKey",
    "AgentSnapshot",
    "Direction",
    "FurnitureItem",
    "FurnitureKind",
    "GenuineAgentKey",
    "Grid",
    "GridPosition",
    "GridRect",
    "MessageSnapshot",
    "Occupant",
    "Office",
    "OfficeIdentity",
    "PresenceStatus",
    "Seat",
    "SnowflakeId",
    "TileCell",
    "TileKind",
    "Zone",
    "parse_commit_ref",
]
