#!/usr/bin/env python3
"""Generate pixel-agents-consumer-contract.yaml from
pixelagents.contracts.outbound's message TypedDicts.

Unlike contracts/pixel_index/contract.yaml (gitignored, regenerated fresh on
every verify.py run), this file is COMMITTED -- it's meant to be read and
reviewed like any other source change. CI (pixel-agents-contract-lint.yml,
and the pixelagents leg of cogs-quality.yml) regenerates it fresh and fails
if the committed copy differs, so it can't silently drift from the code that
actually builds these messages. Never hand-edit it -- edit
pixelagents/contracts/outbound.py (or pixelagents/application/office.py for
existingAgents) and regenerate instead.

Deliberately narrower than "Verified against the real wire protocol" in
docs/corridor-pubsub-design.md: this only covers what
pixelagents.contracts.outbound actually BUILDS today. agentDeselected and
isHeadless/headlessAgents aren't produced by any code yet, so they don't
appear here -- they'll show up automatically, no generator change needed,
once a future PR adds real producers for them. See that doc's "Verifying
this design: two committed contracts" section.

Run: python -m contracts.pixel_agents.generate_consumer_contract
Check without writing: python -m contracts.pixel_agents.generate_consumer_contract --check
"""

from __future__ import annotations

import sys
import typing
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml

from pixelagents.contracts import outbound

CONTRACT_PATH = Path(__file__).with_name("pixel-agents-consumer-contract.yaml")

_HEADER = (
    "# AUTO-GENERATED by contracts/pixel_agents/generate_consumer_contract.py --\n"
    "# do not hand-edit. Committed (unlike contracts/pixel_index/contract.yaml):\n"
    "# CI fails if this differs from a fresh regeneration.\n"
    "# Source of truth: pixelagents/contracts/outbound.py's message TypedDicts.\n"
    "# Regenerate: python -m contracts.pixel_agents.generate_consumer_contract\n"
)

_PRIMITIVES: dict[type, dict[str, str]] = {
    int: {"type": "integer"},
    str: {"type": "string"},
    bool: {"type": "boolean"},
}


def _field_schema(annotation: Any) -> dict[str, Any]:
    origin = typing.get_origin(annotation)
    if origin is typing.Literal:
        values = typing.get_args(annotation)
        if len(values) == 1:
            return {"const": values[0]}
        return {"enum": list(values)}
    if origin is list:
        (item_type,) = typing.get_args(annotation)
        return {"type": "array", "items": _field_schema(item_type)}
    if origin in (dict, Mapping):
        # Coarse -- values not modeled, matching the wire schemas' own
        # additionalProperties-keyed-by-agent-id maps (e.g. existingAgents'
        # agentMeta/folderNames/externalAgents).
        return {"type": "object"}
    if annotation in _PRIMITIVES:
        # A fresh dict every call -- yaml.safe_dump would otherwise notice
        # the shared _PRIMITIVES instance is reused across properties and
        # emit YAML anchors/aliases (&id001/*id001), which defeats the
        # point of committing this file for human review.
        return dict(_PRIMITIVES[annotation])
    raise TypeError(
        f"generate_consumer_contract: no mapping for annotation {annotation!r} -- "
        "extend _field_schema (kept intentionally small; see module docstring)"
    )


def _is_message_typeddict(obj: Any) -> bool:
    return isinstance(obj, type) and typing.is_typeddict(obj) and not obj.__name__.startswith("_")


def build_contract() -> dict[str, Any]:
    messages: dict[str, Any] = {}
    for name in sorted(vars(outbound)):
        obj = getattr(outbound, name)
        if not _is_message_typeddict(obj):
            continue
        hints = typing.get_type_hints(obj)
        (type_const,) = typing.get_args(hints["type"])
        properties = {key: _field_schema(hints[key]) for key in hints}
        messages[type_const] = {
            "typeddict": name,
            "type": "object",
            "additionalProperties": False,
            "required": sorted(obj.__required_keys__),
            "properties": properties,
        }
    return {"version": 1, "messages": messages}


def render() -> str:
    return _HEADER + yaml.safe_dump(build_contract(), sort_keys=False)


def main(check: bool = False) -> int:
    rendered = render()
    if check:
        current = CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{CONTRACT_PATH} is stale -- run "
                "`python -m contracts.pixel_agents.generate_consumer_contract` and commit the result."
            )
            return 1
        print(f"{CONTRACT_PATH} is up to date.")
        return 0
    CONTRACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {CONTRACT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
