"""Loader/cache around `pixelagents.furniture_style_manifest()`.

Deliberately *not* a hand-maintained table -- see
docs/architect-semantic-ir-design.md section 6.4. The manifest is
generated by `pixelagents` at webview-build time and can change out from
under this cog (an operator runs `[p]pixelagents webview rebuild`, or
bumps `webview_vendor.commit`), so this loader re-parses it whenever
`webview_bundle_status().built_commit` changes rather than caching it
forever after the first read.

v2 (docs/architect-semantic-ir-design.md section 6.4): each facing now
carries a real footprint (`FurnitureFacing`), and each style carries
`can_place_on_walls`/`can_place_on_surfaces`. `occupied_cells()` is the
one place footprint occupancy is computed -- the ported equivalent of
Pixel Agents' own `getPlacementBlockedTiles` (`layoutSerializer.ts`),
excluding the top `background_tiles` rows exactly like upstream does.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from ..domain.office_ir import Direction, FurnitureKind, GridPosition

_KIND_BY_NAME: dict[str, FurnitureKind] = {kind.value: kind for kind in FurnitureKind}
_DIRECTION_BY_NAME: dict[str, Direction] = {d.value: d for d in Direction}


@dataclass(frozen=True, slots=True)
class FurnitureFacing:
    """One concrete, real-footprint variant of a style."""

    catalog_id: str
    footprint_width: int
    footprint_height: int
    background_tiles: int


@dataclass(frozen=True, slots=True)
class FurnitureStyle:
    style: str
    kind: FurnitureKind
    label: str
    facings: dict[Direction, FurnitureFacing]
    default_facing: Direction | None
    can_place_on_walls: bool
    can_place_on_surfaces: bool
    # Only set (and only meaningful) when `facings` is empty: the real
    # Pixel Agents asset id + footprint for a facing-less item (e.g.
    # "CUSHIONED_BENCH", "WHITEBOARD"). `style` is a lower-cased
    # LLM/tool-facing handle ("cushioned_bench") that is almost never the
    # real, original-case catalog id -- conflating the two here was a
    # real bug (docs/architect-semantic-ir-design.md section 6.4): every
    # facing-less item silently failed to decode because nothing in Pixel
    # JSON's `furniture[].type` is ever spelled in lower-case.
    catalog_id: str | None = None
    footprint_width: int | None = None
    footprint_height: int | None = None
    background_tiles: int | None = None

    def facing_record(self, facing: Direction | None) -> FurnitureFacing | None:
        """The `FurnitureFacing` for `facing`, or for the facing-less
        catalog_id when `facing is None` and this style has no facings at
        all. `None` if that combination doesn't exist."""

        if facing is None:
            if self.facings or self.catalog_id is None:
                return None
            return FurnitureFacing(
                self.catalog_id,
                self.footprint_width or 1,
                self.footprint_height or 1,
                self.background_tiles or 0,
            )
        return self.facings.get(facing)


class FurnitureStyleManifest:
    """Typed view over one generated `furniture-styles.json` payload."""

    def __init__(self, styles: list[FurnitureStyle]) -> None:
        self._by_style_id: dict[str, FurnitureStyle] = {style.style: style for style in styles}
        self._by_catalog_id: dict[str, tuple[str, Direction | None]] = {}
        for style in styles:
            if not style.facings and style.catalog_id is not None:
                self._by_catalog_id.setdefault(style.catalog_id, (style.style, None))
            for facing, record in style.facings.items():
                self._by_catalog_id[record.catalog_id] = (style.style, facing)

    @classmethod
    def from_raw(cls, raw: dict[str, Any]) -> FurnitureStyleManifest:
        styles = []
        for entry in raw.get("styles", []):
            kind = _KIND_BY_NAME.get(entry["kind"])
            if kind is None:
                continue
            facings = {
                _DIRECTION_BY_NAME[facing]: FurnitureFacing(
                    catalog_id=record["catalog_id"],
                    footprint_width=record["footprint_width"],
                    footprint_height=record["footprint_height"],
                    background_tiles=record.get("background_tiles", 0),
                )
                for facing, record in entry.get("facings", {}).items()
                if facing in _DIRECTION_BY_NAME
            }
            default_facing_raw = entry.get("default_facing")
            styles.append(
                FurnitureStyle(
                    style=entry["style"],
                    kind=kind,
                    label=entry.get("label", entry["style"]),
                    facings=facings,
                    default_facing=_DIRECTION_BY_NAME.get(default_facing_raw)
                    if default_facing_raw
                    else None,
                    can_place_on_walls=bool(entry.get("can_place_on_walls", False)),
                    can_place_on_surfaces=bool(entry.get("can_place_on_surfaces", False)),
                    catalog_id=entry.get("catalog_id"),
                    footprint_width=entry.get("footprint_width"),
                    footprint_height=entry.get("footprint_height"),
                    background_tiles=entry.get("background_tiles"),
                )
            )
        return cls(styles)

    def styles(self) -> list[FurnitureStyle]:
        return list(self._by_style_id.values())

    def style_ids(self) -> list[str]:
        return list(self._by_style_id)

    def by_style_id(self, style_id: str) -> FurnitureStyle | None:
        return self._by_style_id.get(style_id)

    def catalog_id_for(self, style_id: str, facing: Direction | None) -> str | None:
        """The concrete Pixel Agents asset id for `(style_id, facing)`, or
        `None` if that style/facing combination doesn't exist."""

        style = self._by_style_id.get(style_id)
        if style is None:
            return None
        record = style.facing_record(facing)
        return record.catalog_id if record is not None else None

    def occupied_cells(
        self, style_id: str, facing: Direction | None, position: GridPosition
    ) -> list[GridPosition]:
        """Every cell `(style_id, facing)`'s real footprint covers when
        anchored at `position`, excluding the top `background_tiles` rows
        (which don't block placement, matching Pixel Agents' own
        `getPlacementBlockedTiles`). Empty if the style/facing doesn't
        exist -- callers validate style/facing existence separately
        (`by_style_id`/`facing_record`), this never raises."""

        style = self._by_style_id.get(style_id)
        if style is None:
            return []
        record = style.facing_record(facing)
        if record is None:
            return []
        return [
            GridPosition(position.col + dc, position.row + dr)
            for dr in range(record.background_tiles, record.footprint_height)
            for dc in range(record.footprint_width)
        ]

    def background_cells(
        self, style_id: str, facing: Direction | None, position: GridPosition
    ) -> list[GridPosition]:
        """The top `background_tiles` rows `occupied_cells` excludes --
        every cell of `(style_id, facing)`'s footprint that does *not*
        block placement when anchored at `position`. Not just informational:
        since nothing else's placement is rejected for landing here (the
        whole reason `occupied_cells` excludes it), this is exactly where
        an adjacent chair belongs to sit flush against that side of the
        item -- e.g. DESK_FRONT's background row is its north/back edge,
        so a chair "behind" the desk anchors at the same coordinate as
        that row, not one tile further north of the full footprint_height
        bounding box. Empty if the style/facing doesn't exist or has no
        background rows -- never raises, same contract as `occupied_cells`."""

        style = self._by_style_id.get(style_id)
        if style is None:
            return []
        record = style.facing_record(facing)
        if record is None:
            return []
        return [
            GridPosition(position.col + dc, position.row + dr)
            for dr in range(record.background_tiles)
            for dc in range(record.footprint_width)
        ]

    def style_and_facing_for(self, catalog_id: str) -> tuple[str, Direction | None] | None:
        """The reverse lookup `decode()` needs: a Pixel Agents asset id ->
        `(style_id, facing)`, or `None` if the id isn't in this
        manifest (an unrecognized/foreign asset -- see the adapter's
        passthrough handling)."""

        return self._by_catalog_id.get(catalog_id)


class SupportsFurnitureStyles(Protocol):
    def furniture_style_manifest(self) -> dict[str, Any] | None: ...
    def webview_bundle_status(self) -> Any: ...


class FurnitureStyleLoader:
    """Cog-lifetime cache: re-parses the manifest only when the vendored
    commit changes, per `webview_bundle_status().built_commit`."""

    def __init__(self, pixelagents: SupportsFurnitureStyles) -> None:
        self._pixelagents = pixelagents
        self._cached_commit: str | None = None
        self._cached_manifest: FurnitureStyleManifest | None = None

    def styles(self) -> FurnitureStyleManifest:
        """The current style manifest, empty if `pixelagents` hasn't
        built a webview yet (never raises -- an empty manifest just means
        no style validates, which the caller's own validation surfaces as
        an ordinary "unknown style" error, not a crash)."""

        status = self._pixelagents.webview_bundle_status()
        built_commit = getattr(status, "built_commit", None)
        if self._cached_manifest is not None and built_commit == self._cached_commit:
            return self._cached_manifest

        raw = self._pixelagents.furniture_style_manifest()
        manifest = (
            FurnitureStyleManifest.from_raw(raw) if raw is not None else FurnitureStyleManifest([])
        )
        self._cached_commit = built_commit
        self._cached_manifest = manifest
        return manifest


__all__ = [
    "FurnitureFacing",
    "FurnitureStyle",
    "FurnitureStyleLoader",
    "FurnitureStyleManifest",
    "SupportsFurnitureStyles",
]
