#!/usr/bin/env python3
"""Regenerate corridor/office_state.yaml from corridor's own office-state
event catalog -- the office-state counterpart to
contracts/corridor/generate_corridor_contract.py.

Deliberately a separate script writing a separate committed file: office-
state and the Agent*-prefixed pub/sub catalog are two independently-
evolving contracts (docs/cctv-design.md §2.2), not two halves of one.

Committed, not gitignored: CI regenerates this fresh and fails on any
diff from the committed copy, instead of silently overwriting. Never
hand-edit office_state.yaml -- edit corridor/domain/office_state.py and
regenerate.

Run: python -m contracts.corridor.generate_office_contract
Check without writing: python -m contracts.corridor.generate_office_contract --check
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from corridor.office_event_catalog import build_office_contract

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = REPO_ROOT / "corridor" / "office_state.yaml"

_HEADER = (
    "# AUTO-GENERATED by contracts/corridor/generate_office_contract.py --\n"
    "# do not hand-edit. Committed: CI fails if this differs from a fresh\n"
    "# regeneration. Source of truth: corridor/domain/office_state.py.\n"
    "# Regenerate: python -m contracts.corridor.generate_office_contract\n"
)


def render() -> str:
    return _HEADER + yaml.safe_dump(build_office_contract(), sort_keys=False)


def main(check: bool = False) -> int:
    rendered = render()
    if check:
        current = CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{CONTRACT_PATH} is stale -- run "
                "`python -m contracts.corridor.generate_office_contract` and commit the result."
            )
            return 1
        print(f"{CONTRACT_PATH} is up to date.")
        return 0
    CONTRACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {CONTRACT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
