#!/usr/bin/env python3
"""Regenerate corridor/office_state.yaml from the office-state catalog."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from corridor.office_state_catalog import build_contract

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = REPO_ROOT / "corridor" / "office_state.yaml"

_HEADER = (
    "# AUTO-GENERATED by contracts/corridor/generate_office_state_contract.py --\n"
    "# do not hand-edit. Source of truth: corridor/office_state_catalog.py.\n"
    "# Regenerate: python -m contracts.corridor.generate_office_state_contract\n"
)


def render() -> str:
    return _HEADER + yaml.safe_dump(build_contract(), sort_keys=False)


def main(check: bool = False) -> int:
    rendered = render()
    if check:
        current = CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{CONTRACT_PATH} is stale -- run "
                "`python -m contracts.corridor.generate_office_state_contract`."
            )
            return 1
        print(f"{CONTRACT_PATH} is up to date.")
        return 0
    CONTRACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {CONTRACT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
