#!/usr/bin/env python3
"""Regenerate corridor/corridor.yaml from corridor's own event catalog --
corridor's counterpart to
contracts/pixel_agents/generate_consumer_contract.py.

The actual introspection (dataclasses.fields()/typing.get_type_hints()
over corridor.domain) lives in corridor/event_catalog.py, not here:
corridor.yaml moved into the corridor/ package itself (see
docs/corridor.md -- contracts/ is CI-only, no other cog imports it at
runtime, but testbench needs this same schema at runtime to build its UI,
so the introspection had to live somewhere both a real cog and this CI
script could import). This module is now a thin CLI wrapper: render the
committed YAML text and check/write it.

Committed, not gitignored: CI regenerates this fresh and fails on any diff
from the committed copy, instead of silently overwriting. Never hand-edit
corridor.yaml -- edit corridor/domain/models.py and regenerate.

Unlike pixel_agents' contract, there is no separate offline-capture lint
here: corridor's domain types are plain in-process dataclasses, never
serialized to JSON, so there's no "captured wire message" to
runtime-validate the way outbound.py's TypedDicts are. This generator's own
--check mode *is* the full consumer-driven check.

Run: python -m contracts.corridor.generate_corridor_contract
Check without writing: python -m contracts.corridor.generate_corridor_contract --check
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

from corridor.event_catalog import build_contract

REPO_ROOT = Path(__file__).resolve().parents[2]
CONTRACT_PATH = REPO_ROOT / "corridor" / "corridor.yaml"

_HEADER = (
    "# AUTO-GENERATED by contracts/corridor/generate_corridor_contract.py --\n"
    "# do not hand-edit. Committed: CI fails if this differs from a fresh\n"
    "# regeneration. Source of truth: corridor/domain/models.py.\n"
    "# Regenerate: python -m contracts.corridor.generate_corridor_contract\n"
)


def render() -> str:
    return _HEADER + yaml.safe_dump(build_contract(), sort_keys=False)


def main(check: bool = False) -> int:
    rendered = render()
    if check:
        current = CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{CONTRACT_PATH} is stale -- run "
                "`python -m contracts.corridor.generate_corridor_contract` and commit the result."
            )
            return 1
        print(f"{CONTRACT_PATH} is up to date.")
        return 0
    CONTRACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {CONTRACT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
