#!/usr/bin/env python3
"""Generate contracts/corridor/corridor.yaml from corridor.domain's real
dataclasses -- corridor's counterpart to
contracts/pixel_agents/generate_consumer_contract.py, adapted for
dataclasses.fields()/typing.get_type_hints() (corridor's Pub/Sub domain
types are dataclasses, not TypedDicts).

Committed, not gitignored: CI regenerates this fresh and fails on any diff
from the committed copy, instead of silently overwriting. Never hand-edit
corridor.yaml -- edit corridor/domain/models.py and regenerate.

Unlike pixel_agents' contract, there is no separate offline-capture lint
here: corridor's domain types are plain in-process dataclasses, never
serialized to JSON, so there's no "captured wire message" to
runtime-validate the way outbound.py's TypedDicts are. This generator's own
--check mode *is* the full consumer-driven check.

Run: python -m contracts.corridor.generate_corridor_contract
Check without writing: python -m contracts.corridor.generate_corridor_contract --check
"""

from __future__ import annotations

import dataclasses
import sys
import types
import typing
from pathlib import Path
from typing import Any

import yaml

from corridor import domain as corridor_domain

CONTRACT_PATH = Path(__file__).with_name("corridor.yaml")

_HEADER = (
    "# AUTO-GENERATED by contracts/corridor/generate_corridor_contract.py --\n"
    "# do not hand-edit. Committed: CI fails if this differs from a fresh\n"
    "# regeneration. Source of truth: corridor/domain/models.py.\n"
    "# Regenerate: python -m contracts.corridor.generate_corridor_contract\n"
)

# AgentRef and AgentActivity are referenced BY other events' fields, never
# published/subscribed to on their own.
_VALUE_OBJECTS = {"AgentRef", "AgentActivity"}


def _type_name(annotation: Any) -> str:
    origin = typing.get_origin(annotation)
    if origin is typing.Literal:
        return f"Literal[{', '.join(repr(v) for v in typing.get_args(annotation))}]"
    if origin is tuple:
        item_type, _ellipsis = typing.get_args(annotation)
        return f"tuple[{_type_name(item_type)}, ...]"
    if origin is types.UnionType:
        args = [a for a in typing.get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return f"{_type_name(args[0])} | None"
        return " | ".join(_type_name(a) for a in args)
    if isinstance(annotation, type):
        return annotation.__name__
    return str(annotation)


def build_contract() -> dict[str, Any]:
    events: dict[str, Any] = {}
    # Every corridor.domain name starting with "Agent" is part of the
    # pub/sub domain model -- corridor's other domain types (GuildSettings,
    # PermissionGroupDef, ReplyField, ...) are a different contract's
    # concern entirely and deliberately excluded.
    for name in sorted(n for n in corridor_domain.__all__ if n.startswith("Agent")):
        obj = getattr(corridor_domain, name)
        if not (isinstance(obj, type) and dataclasses.is_dataclass(obj)):
            continue  # skips AgentActivityEvent, the union alias
        hints = typing.get_type_hints(obj)
        fields: dict[str, Any] = {}
        for field in dataclasses.fields(obj):
            entry: dict[str, Any] = {"type": _type_name(hints[field.name])}
            if field.default is not dataclasses.MISSING:
                entry["default"] = (
                    list(field.default) if isinstance(field.default, tuple) else field.default
                )
            fields[field.name] = entry
        events[name] = {
            "kind": "value-object" if name in _VALUE_OBJECTS else "event",
            "fields": fields,
        }
    return {
        "version": 1,
        "status": "implemented",
        "source_doc": "docs/corridor-pubsub-design.md",
        "events": events,
    }


def render() -> str:
    return _HEADER + yaml.safe_dump(build_contract(), sort_keys=False)


def main(check: bool = False) -> int:
    rendered = render()
    if check:
        current = CONTRACT_PATH.read_text(encoding="utf-8") if CONTRACT_PATH.exists() else ""
        if current != rendered:
            print(
                f"{CONTRACT_PATH} is stale -- run "
                "`python -m contracts.corridor.generate_corridor_contract` and commit the result."
            )
            return 1
        print(f"{CONTRACT_PATH} is up to date.")
        return 0
    CONTRACT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {CONTRACT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
